// src/lib/apps/notepad/Notepad.svelte
<script lang="ts">
  import MenuBar from '$lib/components/window/MenuBar.svelte';

  export let content: string = '';

  const menus = [
    {
      label: 'File',
      items: [
        { label: 'New' },
        { label: 'Open...' },
        { label: 'Save' },
        { label: 'Save As...' },
        { divider: true },
        { label: 'Page Setup...' },
        { label: 'Print...' },
        { divider: true },
        { label: 'Exit' }
      ]
    },
    {
      label: 'Edit',
      items: [
        { label: 'Undo' },
        { divider: true },
        { label: 'Cut' },
        { label: 'Copy' },
        { label: 'Paste' },
        { label: 'Delete' },
        { divider: true },
        { label: 'Select All' },
        { label: 'Time/Date' }
      ]
    },
    {
      label: 'Search',
      items: [
        { label: 'Find...' },
        { label: 'Find Next' }
      ]
    },
    {
      label: 'Help',
      items: [
        { label: 'Help Topics' },
        { divider: true },
        { label: 'About Notepad' }
      ]
    }
  ];
</script>

<MenuBar {menus} />

<div class="notepad-content">
  <pre>{content}</pre>
</div>

<style>
  .notepad-content {
    width: 100%;
    height: calc(100% - 24px);
    overflow: auto;
    background: white;
    padding: 2px;
  }

  pre {
    margin: 0;
    padding: 4px;
    font-family: 'Fixedsys', 'Courier New', monospace;
    font-size: 12px;
    line-height: 1.4;
    white-space: pre;
    color: black;
  }
</style>

// src/apps/notepad/Notepad.tsx
import type { ComponentProps } from "react";
import { List, Modal, TextArea } from "@react95/core";
import AppWindow from "../../components/window/AppWindow";

interface NotepadProps {
  position: { x: number; y: number };
  onClose: () => void;
  content?: string;
}

export default function Notepad({ position, onClose, content = "" }: NotepadProps) {
  const menu: ComponentProps<typeof Modal>["menu"] = [
    {
      name: "File",
      list: (
        <List width="200px">
          <List.Item>New</List.Item>
          <List.Item>Open...</List.Item>
          <List.Item>Save</List.Item>
          <List.Item>Save As...</List.Item>
          <List.Divider />
          <List.Item>Page Setup...</List.Item>
          <List.Item>Print...</List.Item>
          <List.Divider />
          <List.Item onClick={onClose}>Exit</List.Item>
        </List>
      ),
    },
    {
      name: "Edit",
      list: (
        <List width="200px">
          <List.Item>Undo</List.Item>
          <List.Divider />
          <List.Item>Cut</List.Item>
          <List.Item>Copy</List.Item>
          <List.Item>Paste</List.Item>
          <List.Item>Delete</List.Item>
          <List.Divider />
          <List.Item>Select All</List.Item>
          <List.Item>Time/Date</List.Item>
        </List>
      ),
    },
    {
      name: "Search",
      list: (
        <List width="200px">
          <List.Item>Find...</List.Item>
          <List.Item>Find Next</List.Item>
        </List>
      ),
    },
    {
      name: "Help",
      list: (
        <List width="200px">
          <List.Item>Help Topics</List.Item>
          <List.Divider />
          <List.Item>About Notepad</List.Item>
        </List>
      ),
    },
  ];

  return (
    <AppWindow id="personal-details" position={position} onClose={onClose} menu={menu}>
      <TextArea
        readOnly
        value={content}
        style={{ flex: 1, width: "100%", minHeight: 0, resize: "none" }}
      />
    </AppWindow>
  );
}
