// src/lib/apps/wordpad/WordPad.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import MenuBar from '$lib/components/window/MenuBar.svelte';

  const STORAGE_KEY = 'textarea__main';
  let content = '';

  const menus = [
    {
      label: 'File',
      items: [
        { label: 'New' },
        { label: 'Open...' },
        { label: 'Save' },
        { label: 'Save As...' },
        { divider: true },
        { label: 'Print...' },
        { label: 'Print Preview' },
        { label: 'Page Setup...' },
        { divider: true },
        { label: 'Exit' }
      ]
    },
    {
      label: 'Edit',
      items: [
        { label: 'Undo' },
        { divider: true },
        { label: 'Cut' },
        { label: 'Copy' },
        { label: 'Paste' },
        { label: 'Paste Special...' },
        { label: 'Clear' },
        { label: 'Select All' },
        { divider: true },
        { label: 'Find...' },
        { label: 'Find Next' },
        { label: 'Replace...' }
      ]
    },
    {
      label: 'View',
      items: [
        { label: 'Toolbar' },
        { label: 'Format Bar' },
        { label: 'Ruler' },
        { label: 'Status Bar' }
      ]
    },
    {
      label: 'Insert',
      items: [
        { label: 'Date and Time...' },
        { label: 'Object...' }
      ]
    },
    {
      label: 'Help',
      items: [
        { label: 'Help Topics' },
        { divider: true },
        { label: 'About WordPad' }
      ]
    }
  ];

  onMount(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) content = stored;
  });

  function handleInput(e: Event) {
    const target = e.target as HTMLTextAreaElement;
    content = target.value;
    localStorage.setItem(STORAGE_KEY, content);
  }
</script>

<MenuBar {menus} />

<textarea
  value={content}
  on:input={handleInput}
  placeholder="Type here..."
></textarea>

<style>
  textarea {
    width: 100%;
    height: calc(100% - 24px);
    resize: none;
    border: none;
    padding: 4px;
    font-family: 'Courier New', monospace;
    font-size: 12px;
  }
</style>

// src/apps/wordpad/WordPad.tsx
import { useState } from "react";
import type { ChangeEvent, ComponentProps } from "react";
import { List, Modal, TextArea } from "@react95/core";
import AppWindow from "../../components/window/AppWindow";

const STORAGE_KEY = "textarea__main";

interface WordPadProps {
  position: { x: number; y: number };
  onClose: () => void;
}

export default function WordPad({ position, onClose }: WordPadProps) {
  const [content, setContent] = useState(() => localStorage.getItem(STORAGE_KEY) ?? "");

  function handleInput(event: ChangeEvent<HTMLTextAreaElement>) {
    const value = event.target.value;
    setContent(value);
    localStorage.setItem(STORAGE_KEY, value);
  }

  const menu: ComponentProps<typeof Modal>["menu"] = [
    {
      name: "File",
      list: (
        <List width="200px">
          <List.Item>New</List.Item>
          <List.Item>Open...</List.Item>
          <List.Item>Save</List.Item>
          <List.Item>Save As...</List.Item>
          <List.Divider />
          <List.Item>Print...</List.Item>
          <List.Item>Print Preview</List.Item>
          <List.Item>Page Setup...</List.Item>
          <List.Divider />
          <List.Item onClick={onClose}>Exit</List.Item>
        </List>
      ),
    },
    {
      name: "Edit",
      list: (
        <List width="200px">
          <List.Item>Undo</List.Item>
          <List.Divider />
          <List.Item>Cut</List.Item>
          <List.Item>Copy</List.Item>
          <List.Item>Paste</List.Item>
          <List.Item>Paste Special...</List.Item>
          <List.Item>Clear</List.Item>
          <List.Item>Select All</List.Item>
          <List.Divider />
          <List.Item>Find...</List.Item>
          <List.Item>Find Next</List.Item>
          <List.Item>Replace...</List.Item>
        </List>
      ),
    },
    {
      name: "View",
      list: (
        <List width="200px">
          <List.Item>Toolbar</List.Item>
          <List.Item>Format Bar</List.Item>
          <List.Item>Ruler</List.Item>
          <List.Item>Status Bar</List.Item>
        </List>
      ),
    },
    {
      name: "Insert",
      list: (
        <List width="200px">
          <List.Item>Date and Time...</List.Item>
          <List.Item>Object...</List.Item>
        </List>
      ),
    },
    {
      name: "Help",
      list: (
        <List width="200px">
          <List.Item>Help Topics</List.Item>
          <List.Divider />
          <List.Item>About WordPad</List.Item>
        </List>
      ),
    },
  ];

  return (
    <AppWindow id="wordpad" position={position} onClose={onClose} menu={menu}>
      <TextArea
        value={content}
        onChange={handleInput}
        placeholder="Type here..."
        style={{ flex: 1, width: "100%", minHeight: 0, resize: "none" }}
      />
    </AppWindow>
  );
}
