// src/lib/components/desktop/Desktop.svelte
<script lang="ts">
  import DesktopIcon from './DesktopIcon.svelte';
  import SelectionRectangle from './SelectionRectangle.svelte';
  import Taskbar from './Taskbar.svelte';
  import Window from '$lib/components/window/Window.svelte';
  import WordPad from '$lib/apps/wordpad/WordPad.svelte';
  import MyComputer from '$lib/apps/my-computer/MyComputer.svelte';
  import RecycleBin from '$lib/apps/recycle-bin/RecycleBin.svelte';
  import Notepad from '$lib/apps/notepad/Notepad.svelte';
  import Personal from '$lib/apps/personal/Personal.svelte';
  import { apps } from '$lib/apps';
  import { windows } from '$lib/stores/windows';
  import { desktopSelection, desktopIcons as desktopIconsStore, GRID_SIZE } from '$lib/stores/desktop.svelte';
  import { onMount } from 'svelte';

  // Desktop icons configuration
  const iconConfigs = [
    { id: 'my-computer', icon: apps['my-computer'].icon, label: 'My Computer', appId: 'my-computer', defaultX: 8, defaultY: 8 },
    { id: 'recycle-bin', icon: apps['recycle-bin'].icon, label: 'Recycle Bin', appId: 'recycle-bin', defaultX: 8, defaultY: 83 },
    { id: 'wordpad-doc', icon: apps.wordpad.icon, label: 'Document.rtf', appId: 'wordpad', defaultX: 8, defaultY: 158 },
    { id: 'personal-details', icon: apps['personal-details'].icon, label: 'personal-details.txt', appId: 'personal-details', defaultX: 8, defaultY: 233 },
    { id: 'personal', icon: apps.personal.icon, label: 'Personal', appId: 'personal', defaultX: 8, defaultY: 308 }
  ];

  // Initialize icon positions on mount
  onMount(() => {
    iconConfigs.forEach(config => {
      desktopIconsStore.initPosition(config.id, { x: config.defaultX, y: config.defaultY });
    });
    // Open personal-details.txt by default on first paint.
    windows.open('personal-details', apps['personal-details'].defaultSize);
  });

  // Get position for icon from store
  function getIconPosition(id: string) {
    return desktopIconsStore.positions.get(id) ?? { x: 8, y: 8 };
  }

  // Drag selection state
  let isDragging = $state(false);
  let wasDragging = $state(false);
  let dragStart = $state({ x: 0, y: 0 });
  let dragEnd = $state({ x: 0, y: 0 });

  // Calculate selection rectangle bounds
  let selectionRect = $derived({
    x: Math.min(dragStart.x, dragEnd.x),
    y: Math.min(dragStart.y, dragEnd.y),
    width: Math.abs(dragEnd.x - dragStart.x),
    height: Math.abs(dragEnd.y - dragStart.y)
  });

  function handleDesktopClick(event: MouseEvent) {
    // Only deselect if clicking directly on the desktop background (not during or after drag)
    if (event.target === event.currentTarget && !isDragging && !wasDragging) {
      desktopSelection.deselectAll();
    }
    wasDragging = false;
  }

  function handleMouseDown(event: MouseEvent) {
    // Only start drag-select if clicking directly on desktop background
    if (event.target === event.currentTarget && event.button === 0) {
      isDragging = true;
      dragStart = { x: event.clientX, y: event.clientY };
      dragEnd = { x: event.clientX, y: event.clientY };
    }
  }

  function handleMouseMove(event: MouseEvent) {
    if (isDragging) {
      dragEnd = { x: event.clientX, y: event.clientY };
      updateSelectionFromRect();
    }
  }

  function handleMouseUp() {
    if (isDragging) {
      wasDragging = true;
      isDragging = false;
    }
  }

  function updateSelectionFromRect() {
    const iconElements = document.querySelectorAll('.desktop-icon');
    const selectedIds: string[] = [];

    iconElements.forEach((el) => {
      const rect = el.getBoundingClientRect();
      if (rectsIntersect(selectionRect, rect)) {
        const id = el.getAttribute('data-icon-id');
        if (id) selectedIds.push(id);
      }
    });

    desktopSelection.selectMultiple(selectedIds);
  }

  function rectsIntersect(
    r1: { x: number; y: number; width: number; height: number },
    r2: DOMRect
  ): boolean {
    return !(
      r1.x + r1.width < r2.left ||
      r1.x > r2.right ||
      r1.y + r1.height < r2.top ||
      r1.y > r2.bottom
    );
  }
</script>

<svelte:window on:mousemove={handleMouseMove} on:mouseup={handleMouseUp} />

<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
<div
  class="desktop"
  role="application"
  onclick={handleDesktopClick}
  onmousedown={handleMouseDown}
>
  {#each iconConfigs as config (config.id)}
    <DesktopIcon
      id={config.id}
      icon={config.icon}
      label={config.label}
      appId={config.appId}
      position={getIconPosition(config.id)}
    />
  {/each}
</div>

<SelectionRectangle
  x={selectionRect.x}
  y={selectionRect.y}
  width={selectionRect.width}
  height={selectionRect.height}
  visible={isDragging && selectionRect.width > 2 && selectionRect.height > 2}
/>

<Window
  id="wordpad"
  title={apps.wordpad.title}
  icon={apps.wordpad.icon}
  width={apps.wordpad.defaultSize.width}
  height={apps.wordpad.defaultSize.height}
>
  <WordPad />
</Window>

<Window
  id="my-computer"
  title={apps['my-computer'].title}
  icon={apps['my-computer'].icon}
  width={apps['my-computer'].defaultSize.width}
  height={apps['my-computer'].defaultSize.height}
>
  <MyComputer />
</Window>

<Window
  id="recycle-bin"
  title={apps['recycle-bin'].title}
  icon={apps['recycle-bin'].icon}
  width={apps['recycle-bin'].defaultSize.width}
  height={apps['recycle-bin'].defaultSize.height}
>
  <RecycleBin />
</Window>

<Window
  id="personal-details"
  title={apps['personal-details'].title}
  icon={apps['personal-details'].icon}
  width={apps['personal-details'].defaultSize.width}
  height={apps['personal-details'].defaultSize.height}
>
  <Notepad content={`Hi, I'm Jonas. I'm a software developer based in Oslo, Norway. I'm super passionate about computers, technology, animal rights and tinkering. Currently working on https://pep.dev.

I love to use my skills to make people's lives better in whatever ways I can and to build things that do so. If you do too, feel free to reach out at: jonas.jensen@msn.com`} />
</Window>

<Window
  id="personal"
  title={apps.personal.title}
  icon={apps.personal.icon}
  width={apps.personal.defaultSize.width}
  height={apps.personal.defaultSize.height}
>
  <Personal />
</Window>

<Taskbar />

<style>
  .desktop {
    position: relative;
    height: calc(100vh - 28px);
    padding: 8px;
  }
</style>

// src/components/desktop/Desktop.tsx
import { Fragment, useCallback, useState } from "react";
import type { ReactElement } from "react";
import { List, TaskBar, useModal } from "@react95/core";
import { HelpBook, PowerOff } from "@react95/icons";
import DesktopIcon from "./DesktopIcon";
import WordPad from "../../apps/wordpad/WordPad";
import MyComputer from "../../apps/my-computer/MyComputer";
import RecycleBin from "../../apps/recycle-bin/RecycleBin";
import Notepad from "../../apps/notepad/Notepad";
import Personal from "../../apps/personal/Personal";
import { apps, type AppId } from "../../apps/registry";
import styles from "./Desktop.module.css";

// Desktop icons down the left edge. Labels differ from window titles (e.g. the
// file name rather than "… - WordPad").
const DESKTOP_ICONS: { id: string; appId: AppId; label: string }[] = [
  { id: "my-computer", appId: "my-computer", label: "My Computer" },
  { id: "recycle-bin", appId: "recycle-bin", label: "Recycle Bin" },
  { id: "wordpad", appId: "wordpad", label: "Document.rtf" },
  { id: "personal-details", appId: "personal-details", label: "personal-details.txt" },
  { id: "personal", appId: "personal", label: "Personal" },
];

const NOTEPAD_CONTENT = `Hi, I'm Jonas. I'm a software developer based in Oslo, Norway. I'm super passionate about computers, technology, animal rights and tinkering. Currently working on https://pep.dev.

I love to use my skills to make people's lives better in whatever ways I can and to build things that do so. If you do too, feel free to reach out at: jonas.jensen@msn.com`;

interface AppSlotProps {
  position: { x: number; y: number };
  onClose: () => void;
}

// Maps each app id to its window. React95's <Modal> base sits at top:50px,
// left:0; dragOptions.defaultPosition translates from there.
const renderers: Record<AppId, (props: AppSlotProps) => ReactElement> = {
  "personal-details": (props) => <Notepad {...props} content={NOTEPAD_CONTENT} />,
  wordpad: (props) => <WordPad {...props} />,
  "my-computer": (props) => <MyComputer {...props} />,
  "recycle-bin": (props) => <RecycleBin {...props} />,
  personal: (props) => <Personal {...props} />,
};

// Desktop icons occupy a ~96px column on the left; spawn windows clear of it
// when the viewport has room, otherwise fall back to a top-left cascade.
const ICON_COLUMN = 96;
function spawnPosition(index: number, width: number): { x: number; y: number } {
  const offset = (index % 8) * 30;
  const vw = typeof window !== "undefined" ? window.innerWidth : 1024;
  const clearX = ICON_COLUMN + offset;
  const x = clearX + width + 16 <= vw ? clearX : 50 + offset;
  return { x, y: offset };
}

export default function Desktop() {
  const { focus, restore } = useModal();
  const [selected, setSelected] = useState<string | null>(null);
  const [openWindows, setOpenWindows] = useState<{ id: AppId; pos: { x: number; y: number } }[]>(
    () => [
      { id: "personal-details", pos: spawnPosition(0, apps["personal-details"].defaultSize.width) },
    ],
  );

  const openApp = useCallback(
    (id: AppId) => {
      setOpenWindows((prev) => {
        if (prev.some((w) => w.id === id)) return prev;
        return [...prev, { id, pos: spawnPosition(prev.length, apps[id].defaultSize.width) }];
      });
      // Bring an already-open (or freshly-restored) window to the front.
      restore(id);
      focus(id);
    },
    [focus, restore],
  );

  const closeApp = useCallback((id: AppId) => {
    setOpenWindows((prev) => prev.filter((w) => w.id !== id));
  }, []);

  return (
    <div
      className={styles.desktop}
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) setSelected(null);
      }}
    >
      <div className={styles.icons}>
        {DESKTOP_ICONS.map((di) => (
          <DesktopIcon
            key={di.id}
            icon={apps[di.appId].icon}
            label={di.label}
            selected={selected === di.id}
            onSelect={() => setSelected(di.id)}
            onOpen={() => openApp(di.appId)}
          />
        ))}
      </div>

      {openWindows.map(({ id, pos }) => (
        <Fragment key={id}>
          {renderers[id]({ position: pos, onClose: () => closeApp(id) })}
        </Fragment>
      ))}

      <TaskBar
        list={
          <List>
            <List.Item icon={apps.personal.icon} onClick={() => openApp("personal")}>
              Personal
            </List.Item>
            <List.Item icon={apps.wordpad.icon} onClick={() => openApp("wordpad")}>
              Document.rtf
            </List.Item>
            <List.Item
              icon={apps["personal-details"].icon}
              onClick={() => openApp("personal-details")}
            >
              personal-details.txt
            </List.Item>
            <List.Item icon={apps["my-computer"].icon} onClick={() => openApp("my-computer")}>
              My Computer
            </List.Item>
            <List.Item icon={apps["recycle-bin"].icon} onClick={() => openApp("recycle-bin")}>
              Recycle Bin
            </List.Item>
            <List.Divider />
            <List.Item icon={<HelpBook variant="32x32_4" />}>Help</List.Item>
            <List.Item icon={<PowerOff variant="32x32_4" />}>Shut Down...</List.Item>
          </List>
        }
      />
    </div>
  );
}
